name: "Build iOS app"

on:
  workflow_dispatch:
    branches: [main]

jobs:
  build_and_package:
    runs-on: macos-latest
    steps:
      - name: Check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pod install

      - name: Build for simulator
        run: |
          xcodebuild -scheme "UpgradeUpsell" \
          -workspace "UpgradeUpsell.xcworkspace" \
          -sdk iphonesimulator \
          -configuration Debug \
          clean build

      - name: Package IPA
        env:
          EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
        run: |
          EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
          echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
          xcodebuild -exportArchive -archivePath $RUNNER_TEMP/UpgradeUpsell.xcarchive -exportOptionsPlist $EXPORT_OPTS_PATH -exportPath $RUNNER_TEMP/build

      - name: Upload application
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ${{ runner.temp }}/build/UpgradeUpsell.ipa
          retention-days: 3
