name: Build and Distribute UpgradeUpsell

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app  # Adjust the Xcode path to match your Xcode version

    - name: Build and Archive
      run: xcodebuild -workspace UpgradeUpsell.xcworkspace -scheme UpgradeUpsell -archivePath build/UpgradeUpsell.xcarchive archive

    - name: Create IPA
      run: xcodebuild -exportArchive -archivePath build/UpgradeUpsell.xcarchive -exportPath build -exportOptionsPlist ExportOptions.plist  # Adjust the options as needed

    - name: Upload IPA as artifact
      uses: actions/upload-artifact@v2
      with:
        name: UpgradeUpsell
        path: build/UpgradeUpsell.ipa
