name: "Build and Distribute UpgradeUpsell"

on:
  # Trigger the workflow manually or on a specific branch (e.g., main)
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow on


jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build archive
        run: |
          xcodebuild -workspace UpgradeUpsell.xcworkspace \
          -scheme UpgradeUpsell \
          -archivePath $RUNNER_TEMP/UpgradeUpsell.xcarchive \
          -sdk iphoneos \
          -configuration Debug \
          -destination generic/platform=iOS \
          clean archive

      - name: Export IPA
        env:
          EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
        run: |
          EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
          echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
          xcodebuild -exportArchive -archivePath $RUNNER_TEMP/UpgradeUpsell.xcarchive -exportOptionsPlist $EXPORT_OPTS_PATH -exportPath $RUNNER_TEMP/build

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: UpgradeUpsell
          path: ${{ runner.temp }}/build/UpgradeUpsell.ipa
