name: iOS Build and Test

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        pod install

    - name: Build and Test iOS App
      run: |
        xcodebuild -workspace UpgradeUpsell.xcworkspace -scheme UpgradeUpsell -destination 'platform=iOS Simulator,name=iPhone 13' build test
